// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gm.Game = (function(_super) {

    __extends(Game, _super);

    function Game() {
      Game.__super__.constructor.call(this, gm.WIDTH, gm.HEIGHT, Phaser.CANVAS, 'game');
      this.state.add('load', gm.Load, true);
      this.state.add('level', gm.Level, false);
      this.state.add('title', gm.Title, false);
    }

    return Game;

  })(Phaser.Game);

}).call(this);
