// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gm.Counterweight = (function(_super) {

    __extends(Counterweight, _super);

    function Counterweight(game, xx, yy, triggers, data) {
      this.game = game;
      Counterweight.__super__.constructor.call(this, this.game, xx, yy, 3, 3, 'counterweight', 'counterweight', triggers, data);
      this.rope = this.game.add.tileSprite(this.x + this.width / 2 - 7, 0, 15, -this.y - 1000, 'chain');
      this.rope.tint = gm.DARK_TINT;
    }

    Counterweight.prototype.update = function() {
      Counterweight.__super__.update.call(this);
      this.rope.alpha = this.alpha;
      return this.rope.y = this.y;
    };

    return Counterweight;

  })(gm.LiftablePlatform);

}).call(this);
