// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gm.Crack = (function(_super) {

    __extends(Crack, _super);

    function Crack(game, xx, yy, mode) {
      Crack.__super__.constructor.call(this, game, xx, yy, 'crack_1', mode);
      this.height -= 30;
      this.y -= this.height - gm.TILE_SIZE;
      this.game.physics.enable(this, Phaser.Physics.ARCADE);
      this.body.setSize(10, 50, 50, 50);
      this.body.allowGravity = false;
      this.body.immovable = true;
      this.body.checkCollision.up = false;
      this.body.checkCollision.down = false;
    }

    return Crack;

  })(gm.Entity);

}).call(this);
