// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gm.DynamicPlatform = (function(_super) {

    __extends(DynamicPlatform, _super);

    function DynamicPlatform(game, xx, yy, ww, hh, keyRe, keyIm, triggers, data) {
      this.game = game;
      DynamicPlatform.__super__.constructor.call(this, game, xx, yy, ww, hh, keyRe, keyIm, data);
      this.triggers = triggers || [];
    }

    DynamicPlatform.prototype.applyEffect = function(sprite) {};

    DynamicPlatform.prototype.resetTriggers = function() {
      var t, _i, _len, _ref, _results;
      _ref = this.triggers;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        t = _ref[_i];
        _results.push(t.reset());
      }
      return _results;
    };

    DynamicPlatform.prototype.allTriggersFired = function() {
      var t, _i, _len, _ref;
      _ref = this.triggers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        t = _ref[_i];
        if (!t.fired) {
          return false;
        }
      }
      return true;
    };

    return DynamicPlatform;

  })(gm.Platform);

}).call(this);
