// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gm.Entity = (function(_super) {

    __extends(Entity, _super);

    function Entity(game, xx, yy, key, mode) {
      this.game = game;
      this.xx = xx;
      this.yy = yy;
      this.mode = mode != null ? mode : null;
      Entity.__super__.constructor.call(this, this.game, this.xx * gm.TILE_SIZE, this.yy * gm.TILE_SIZE, key);
      this.enabled = true;
    }

    Entity.prototype.enable = function() {
      this.enabled = true;
      return this.alpha = 1;
    };

    Entity.prototype.disable = function() {
      this.enabled = false;
      return this.alpha = 0;
    };

    return Entity;

  })(Phaser.Sprite);

}).call(this);
