// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gm.Item = (function(_super) {

    __extends(Item, _super);

    function Item(game, id, xx, yy, mode) {
      var ratio, _ref;
      this.game = game;
      this.id = id;
      Item.__super__.constructor.call(this, this.game, xx, yy, 'item_' + this.id, (_ref = parseInt(mode)) != null ? _ref : null);
      this.game.physics.enable(this, Phaser.Physics.ARCADE);
      this.body.allowGravity = false;
      this.game.add.existing(this);
      ratio = this.width / this.height;
      this.height = gm.TILE_SIZE;
      this.width = gm.TILE_SIZE * ratio;
      this.y -= this.height / 2 - gm.TILE_SIZE / 2 + 5;
    }

    Item.prototype.enable = function() {
      Item.__super__.enable.call(this);
      return this.body.checkCollision.none = false;
    };

    Item.prototype.disable = function() {
      Item.__super__.disable.call(this);
      return this.body.checkCollision.none = true;
    };

    return Item;

  })(gm.Entity);

}).call(this);
