// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gm.LightBeam = (function(_super) {

    __extends(LightBeam, _super);

    function LightBeam(game, xx, yy) {
      var SIZE, tween;
      this.game = game;
      this.xx = xx;
      this.yy = yy;
      SIZE = 400;
      LightBeam.__super__.constructor.call(this, this.game, xx * gm.TILE_SIZE - SIZE / 2 + gm.TILE_SIZE / 2, yy * gm.TILE_SIZE - SIZE / 2 + gm.TILE_SIZE / 2, 'lightbeam');
      this.alpha = 0.85;
      this.tint = 0xffaa55;
      this.width = this.height = SIZE;
      this.blendMode = PIXI.blendModes.ADD;
      tween = this.game.add.tween(this).to({
        x: this.x + 20,
        y: this.y + 20,
        width: this.width - 40,
        height: this.height - 40,
        alpha: 0.8
      }, Math.random() * 1000 + 3000, Phaser.Easing.Elastic.InOut, true, 0, -1);
      tween.yoyo(true);
    }

    return LightBeam;

  })(Phaser.Sprite);

}).call(this);
