// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gm.Trap = (function(_super) {

    __extends(Trap, _super);

    function Trap(game, xx, yy, ww, hh, keyRe, keyIm, triggers, data) {
      Trap.__super__.constructor.call(this, game, xx, yy, ww, hh, keyRe, keyIm, triggers, data);
    }

    return Trap;

  })(gm.LiftablePlatform);

}).call(this);
