// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gm.TextTrigger = (function(_super) {

    __extends(TextTrigger, _super);

    function TextTrigger(id, x, y, mode, text, data) {
      this.text = text;
      TextTrigger.__super__.constructor.call(this, id, x, y, mode, true, data);
    }

    return TextTrigger;

  })(gm.Trigger);

}).call(this);
