// Generated by CoffeeScript 1.4.0
(function() {

  gm.Trigger = (function() {

    function Trigger(id, x, y, mode, automatic, data) {
      var _ref;
      this.id = id;
      this.x = x;
      this.y = y;
      this.automatic = automatic != null ? automatic : false;
      this.data = data != null ? data : {};
      this.mode = (_ref = parseInt(mode)) != null ? _ref : null;
      this.fired = false;
    }

    Trigger.prototype.fire = function() {
      return this.fired = true;
    };

    Trigger.prototype.reset = function() {
      return this.fired = false;
    };

    return Trigger;

  })();

}).call(this);
